# Enable debug level to see output of "logging" exporter
log-level: DEBUG

receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
    reconnection_delay: 2s
  jaeger:
    protocols:
      thrift-http:
        endpoint: "0.0.0.0:14268"


exporters:
  opencensus:
    endpoint: "otel-collector:55678"
  logging:
    loglevel: debug

processors:
  batch:

pipelines:
  traces:
    receivers: [opencensus, jaeger]
    exporters: [opencensus, logging]
    processors: [batch]
  metrics:
    receivers: [opencensus]
    exporters: [logging,opencensus]

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages]

