# Enable debug level to see output of "logging" exporter
log-level: DEBUG

receivers:
  opencensus:
    endpoint: 0.0.0.0:55678

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  zipkin:
    url: "http://zipkin:9411/api/v2/spans"

processors:
  batch:

pipelines:
  traces:
    receivers: [opencensus]
    exporters: [logging, zipkin]
    processors: [batch]
  metrics:
    receivers: [opencensus]
    exporters: [logging,prometheus]

extensions:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages]

